@extends('layouts.admin.app')
@section('title', translate('messages.Push Notifications'))
@section('content')
<div class="content container-fluid">
    <div class="page-header"><h1 class="page-header-title"><span class="page-header-icon"><i class="tio-notifications-on"></i></span>{{ translate('messages.Ride Push Notifications') }}</h1><p class="page-header-text mb-0">{{ translate('messages.Send Ride promotions to all passengers or a selected zone.') }}</p></div>
    @include('admin-views.ride-hailing.partials.alerts')
    <div class="card mb-3"><div class="card-header"><h5 class="card-title">{{ translate('messages.Create and Send Notification') }}</h5></div><div class="card-body"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.ride-hailing.push-notifications.store') }}">@csrf
        <div class="row"><div class="col-md-6 mb-3"><label class="input-label">{{ translate('messages.Title') }}</label><input name="title" maxlength="191" required class="form-control" value="{{ old('title') }}"></div><div class="col-md-6 mb-3"><label class="input-label">{{ translate('messages.Target Zone') }}</label><select name="zone_id" class="form-control"><option value="">{{ translate('messages.All Zones') }}</option>@foreach($zones as $zone)<option value="{{ $zone->id }}" @selected((string)old('zone_id') === (string)$zone->id)>{{ $zone->name }}</option>@endforeach</select></div>
        <div class="col-md-4 mb-3"><label class="input-label">{{ translate('messages.Action') }}</label><select name="action_type" class="form-control ride-action-type"><option value="ride_home">{{ translate('messages.Open Ride Home') }}</option><option value="coupon">{{ translate('messages.Apply Ride Coupon') }}</option><option value="url">{{ translate('messages.Open URL') }}</option></select></div><div class="col-md-4 mb-3 ride-action-value"><label class="input-label">{{ translate('messages.Action Value') }}</label><input name="action_value" class="form-control" value="{{ old('action_value') }}" list="ride-coupon-codes"></div><div class="col-md-4 mb-3"><label class="input-label">{{ translate('messages.Image (Optional)') }}</label><input type="file" name="image" accept="image/png,image/jpeg,image/webp" class="form-control"></div><div class="col-12 mb-3"><label class="input-label">{{ translate('messages.Message') }}</label><textarea name="description" class="form-control" rows="3" maxlength="1000" required>{{ old('description') }}</textarea></div></div>
        <datalist id="ride-coupon-codes">@foreach($coupons as $coupon)<option value="{{ $coupon->code }}">{{ $coupon->title }}</option>@endforeach</datalist><div class="text-right"><button class="btn btn--primary"><i class="tio-send mr-1"></i>{{ translate('messages.Send Notification') }}</button></div>
    </form></div></div>
    <div class="card"><div class="card-header"><h5 class="card-title">{{ translate('messages.Notification History') }} <span class="badge badge-soft-dark">{{ $notifications->total() }}</span></h5><form class="search-form min--270"><div class="input-group input--group"><input name="search" type="search" value="{{ $search }}" class="form-control" placeholder="{{ translate('messages.Search notifications') }}"><button class="btn btn--secondary"><i class="tio-search"></i></button></div></form></div><div class="table-responsive"><table class="table table-borderless table-thead-bordered table-align-middle card-table"><thead class="thead-light"><tr><th>{{ translate('messages.Notification') }}</th><th>{{ translate('messages.Audience') }}</th><th>{{ translate('messages.Action') }}</th><th>{{ translate('messages.Sent At') }}</th><th>{{ translate('messages.Feed Status') }}</th><th class="text-center">{{ translate('messages.Action') }}</th></tr></thead><tbody>
    @forelse($notifications as $item)<tr><td><strong>{{ $item->title }}</strong><br><small class="text-muted">{{ \Illuminate\Support\Str::limit($item->description, 70) }}</small></td><td>{{ $item->zone?->name ?? translate('messages.All Zones') }}</td><td><span class="badge badge-soft-info">{{ ucfirst(str_replace('_', ' ', $item->action_type)) }}</span><br><small>{{ $item->delivery_status }}</small></td><td>{{ $item->sent_at?->format('d M Y, h:i A') ?? '-' }}</td><td><form method="POST" action="{{ route('admin.ride-hailing.push-notifications.status', $item) }}">@csrf @method('PUT')<label class="toggle-switch mb-0"><input type="checkbox" class="toggle-switch-input" onchange="this.form.submit()" @checked($item->status)><span class="toggle-switch-label"><span class="toggle-switch-indicator"></span></span></label></form></td><td><div class="btn--container justify-content-center"><form method="POST" action="{{ route('admin.ride-hailing.push-notifications.resend', $item) }}">@csrf<button class="btn btn-sm btn-outline-info btn-icon" title="{{ translate('messages.Send Again') }}"><i class="tio-refresh"></i></button></form><form method="POST" action="{{ route('admin.ride-hailing.push-notifications.destroy', $item) }}" onsubmit="return confirm('{{ translate('messages.Delete this notification?') }}')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger btn-icon"><i class="tio-delete"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center py-5">{{ translate('messages.No Ride notifications found.') }}</td></tr>@endforelse
    </tbody></table></div>@if($notifications->hasPages())<div class="card-footer">{{ $notifications->links() }}</div>@endif</div>
</div>
@endsection
@push('script_2')<script>$(function(){function sync(){const type=$('.ride-action-type').val();$('.ride-action-value').toggle(type!=='ride_home');}$('.ride-action-type').on('change',sync);sync();});</script>@endpush
