@extends('layouts.admin.app')
@section('title', translate('messages.Ride Banners'))
@section('content')
@php($editing = isset($banner) && $banner)
<div class="content container-fluid">
    <div class="page-header"><h1 class="page-header-title"><span class="page-header-icon"><i class="tio-image"></i></span>{{ translate('messages.Ride Banners') }}</h1><p class="page-header-text mb-0">{{ translate('messages.Show targeted promotions inside the passenger Ride experience.') }}</p></div>
    @include('admin-views.ride-hailing.partials.alerts')
    <div class="card mb-3"><div class="card-header"><h5 class="card-title">{{ translate($editing ? 'messages.Edit Ride Banner' : 'messages.Create Ride Banner') }}</h5>@if($editing)<a href="{{ route('admin.ride-hailing.banners.index') }}" class="btn btn-outline-secondary btn-sm"><i class="tio-clear mr-1"></i>{{ translate('messages.Cancel Edit') }}</a>@endif</div><div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('admin.ride-hailing.banners.update', $banner) : route('admin.ride-hailing.banners.store') }}">@csrf @if($editing) @method('PUT') @endif
            <div class="row">
                <div class="col-md-6 col-lg-4 mb-3"><label class="input-label">{{ translate('messages.Title') }}</label><input name="title" class="form-control" required maxlength="191" value="{{ old('title', $banner?->title) }}"></div>
                <div class="col-md-6 col-lg-4 mb-3"><label class="input-label">{{ translate('messages.Pickup Zone') }}</label><select name="zone_id" class="form-control"><option value="">{{ translate('messages.All Zones') }}</option>@foreach($zones as $zone)<option value="{{ $zone->id }}" @selected((string)old('zone_id', $banner?->zone_id) === (string)$zone->id)>{{ $zone->name }}</option>@endforeach</select></div>
                <div class="col-md-6 col-lg-4 mb-3"><label class="input-label">{{ translate('messages.Ride Category') }}</label><select name="ride_category_id" class="form-control"><option value="">{{ translate('messages.All Categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('ride_category_id', $banner?->ride_category_id) === (string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
                <div class="col-md-6 col-lg-3 mb-3"><label class="input-label">{{ translate('messages.Starts At') }}</label><input type="datetime-local" name="starts_at" class="form-control" required value="{{ old('starts_at', $banner?->starts_at?->format('Y-m-d\TH:i')) }}"></div>
                <div class="col-md-6 col-lg-3 mb-3"><label class="input-label">{{ translate('messages.Expires At') }}</label><input type="datetime-local" name="expires_at" class="form-control" required value="{{ old('expires_at', $banner?->expires_at?->format('Y-m-d\TH:i')) }}"></div>
                <div class="col-md-6 col-lg-2 mb-3"><label class="input-label">{{ translate('messages.Sort Order') }}</label><input type="number" min="0" name="sort_order" class="form-control" value="{{ old('sort_order', $banner?->sort_order ?? 0) }}"></div>
                <div class="col-md-6 col-lg-4 mb-3"><label class="input-label">{{ translate('messages.Action') }}</label><select name="action_type" class="form-control ride-action-type" required><option value="none" @selected(old('action_type', $banner?->action_type) === 'none')>{{ translate('messages.No Action') }}</option><option value="ride_home" @selected(old('action_type', $banner?->action_type) === 'ride_home')>{{ translate('messages.Open Ride Home') }}</option><option value="coupon" @selected(old('action_type', $banner?->action_type) === 'coupon')>{{ translate('messages.Apply Ride Coupon') }}</option><option value="url" @selected(old('action_type', $banner?->action_type) === 'url')>{{ translate('messages.Open URL') }}</option></select></div>
                <div class="col-md-6 mb-3 ride-action-value"><label class="input-label">{{ translate('messages.Action Value') }}</label><input name="action_value" class="form-control" value="{{ old('action_value', $banner?->action_value) }}" list="ride-coupon-codes"><small class="text-muted">{{ translate('messages.Enter a Ride coupon code or a complete HTTPS URL.') }}</small></div>
                <div class="col-md-6 mb-3"><label class="input-label">{{ translate('messages.Banner Image') }}</label><input type="file" name="image" accept="image/png,image/jpeg,image/webp" class="form-control" @required(!$editing)>@if($editing)<small><a href="{{ $banner->image_full_url }}" target="_blank">{{ translate('messages.View Current Image') }}</a></small>@endif</div>
                <div class="col-12 mb-3"><label class="input-label">{{ translate('messages.Description') }}</label><textarea name="description" maxlength="1000" class="form-control" rows="2">{{ old('description', $banner?->description) }}</textarea></div>
            </div><datalist id="ride-coupon-codes">@foreach($coupons as $coupon)<option value="{{ $coupon->code }}">{{ $coupon->title }}</option>@endforeach</datalist>
            <div class="text-right"><button class="btn btn--primary"><i class="tio-save mr-1"></i>{{ translate($editing ? 'messages.Update Banner' : 'messages.Create Banner') }}</button></div>
        </form>
    </div></div>
    <div class="card"><div class="card-header"><h5 class="card-title">{{ translate('messages.Ride Banner List') }} <span class="badge badge-soft-dark">{{ $banners->total() }}</span></h5><form class="search-form min--270"><div class="input-group input--group"><input type="search" name="search" value="{{ $search }}" class="form-control" placeholder="{{ translate('messages.Search banners') }}"><button class="btn btn--secondary"><i class="tio-search"></i></button></div></form></div>
        <div class="table-responsive"><table class="table table-borderless table-thead-bordered table-align-middle card-table"><thead class="thead-light"><tr><th>{{ translate('messages.Banner') }}</th><th>{{ translate('messages.Scope') }}</th><th>{{ translate('messages.Duration') }}</th><th>{{ translate('messages.Action') }}</th><th>{{ translate('messages.Status') }}</th><th class="text-center">{{ translate('messages.Action') }}</th></tr></thead><tbody>
        @forelse($banners as $item)<tr><td><div class="d-flex align-items-center"><img src="{{ $item->image_full_url }}" alt="" class="rounded mr-3" style="width:72px;height:44px;object-fit:cover"><div><strong>{{ $item->title }}</strong><br><small class="text-muted">{{ \Illuminate\Support\Str::limit($item->description, 55) }}</small></div></div></td><td>{{ $item->zone?->name ?? translate('messages.All Zones') }}<br><small>{{ $item->category?->name ?? translate('messages.All Categories') }}</small></td><td><small>{{ $item->starts_at->format('d M Y, h:i A') }}<br>{{ $item->expires_at->format('d M Y, h:i A') }}</small></td><td><span class="badge badge-soft-info">{{ ucfirst(str_replace('_', ' ', $item->action_type)) }}</span></td><td><form method="POST" action="{{ route('admin.ride-hailing.banners.status', $item) }}">@csrf @method('PUT')<label class="toggle-switch mb-0"><input type="checkbox" class="toggle-switch-input" onchange="this.form.submit()" @checked($item->status)><span class="toggle-switch-label"><span class="toggle-switch-indicator"></span></span></label></form></td><td><div class="btn--container justify-content-center"><a class="btn btn-sm btn-outline-primary btn-icon" href="{{ route('admin.ride-hailing.banners.edit', $item) }}"><i class="tio-edit"></i></a><form method="POST" action="{{ route('admin.ride-hailing.banners.destroy', $item) }}" onsubmit="return confirm('{{ translate('messages.Delete this Ride banner?') }}')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger btn-icon"><i class="tio-delete"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center py-5">{{ translate('messages.No Ride banners found.') }}</td></tr>@endforelse
        </tbody></table></div>@if($banners->hasPages())<div class="card-footer">{{ $banners->links() }}</div>@endif
    </div>
</div>
@endsection
@push('script_2')<script>$(function(){function sync(){const type=$('.ride-action-type').val();$('.ride-action-value').toggle(type==='coupon'||type==='url');}$('.ride-action-type').on('change',sync);sync();});</script>@endpush
