@extends('layouts.admin.app')

@section('title', translate('messages.Ride Coupons'))

@section('content')
@php
    $editing = isset($coupon) && $coupon;
    $selectedZones = old('zone_ids', $editing ? ($coupon->zone_ids ?? []) : []);
    $selectedCategories = old('ride_category_ids', $editing ? ($coupon->ride_category_ids ?? []) : []);
    $selectedMethods = old('payment_methods', $editing ? ($coupon->payment_methods ?? ['all']) : ['all']);
@endphp
<div class="content container-fluid">
    <div class="page-header"><h1 class="page-header-title"><span class="page-header-icon"><i class="tio-gift"></i></span>{{ translate('messages.Ride Coupons') }}</h1><p class="page-header-text mb-0">{{ translate('messages.Create admin-sponsored discounts for eligible passenger Rides.') }}</p></div>
    @include('admin-views.ride-hailing.partials.alerts')

    <div class="card mb-3"><div class="card-header"><h5 class="card-title">{{ translate($editing ? 'messages.Edit Ride Coupon' : 'messages.Create Ride Coupon') }}</h5>@if($editing)<a href="{{ route('admin.ride-hailing.coupons.index') }}" class="btn btn-outline-secondary btn-sm"><i class="tio-clear mr-1"></i>{{ translate('messages.Cancel Edit') }}</a>@endif</div><div class="card-body">
        <form method="POST" action="{{ $editing ? route('admin.ride-hailing.coupons.update', $coupon) : route('admin.ride-hailing.coupons.store') }}">@csrf @if($editing) @method('PUT') @endif
            <div class="row g-3">
                <div class="col-md-6 col-lg-4"><label class="input-label">{{ translate('messages.Title') }}</label><input name="title" class="form-control" maxlength="191" required value="{{ old('title', $coupon?->title) }}" placeholder="{{ translate('messages.Example: First Ride Offer') }}"></div>
                <div class="col-md-6 col-lg-4"><label class="input-label">{{ translate('messages.Coupon Code') }}</label><input name="code" class="form-control text-uppercase" maxlength="100" required value="{{ old('code', $coupon?->code) }}" placeholder="ZAQOOTA20"></div>
                <div class="col-md-6 col-lg-2"><label class="input-label">{{ translate('messages.Discount Type') }}</label><select name="discount_type" id="ride-discount-type" class="form-control" required><option value="amount" @selected(old('discount_type', $coupon?->discount_type) === 'amount')>{{ translate('messages.Fixed Amount') }}</option><option value="percent" @selected(old('discount_type', $coupon?->discount_type) === 'percent')>{{ translate('messages.Percentage') }}</option></select></div>
                <div class="col-md-6 col-lg-2"><label class="input-label">{{ translate('messages.Discount') }}</label><input type="number" name="discount" step="0.01" min="0.01" class="form-control" required value="{{ old('discount', $coupon?->discount) }}"></div>
                <div class="col-md-6 col-lg-3" id="ride-max-discount-wrap"><label class="input-label">{{ translate('messages.Maximum Discount') }}</label><input type="number" name="max_discount" step="0.01" min="0" class="form-control" value="{{ old('max_discount', $coupon?->max_discount ?? 0) }}"></div>
                <div class="col-md-6 col-lg-3"><label class="input-label">{{ translate('messages.Minimum Accepted Fare') }}</label><input type="number" name="min_fare" step="0.01" min="0" class="form-control" value="{{ old('min_fare', $coupon?->min_fare ?? 0) }}"></div>
                <div class="col-md-6 col-lg-3"><label class="input-label">{{ translate('messages.Total Usage Limit') }}</label><input type="number" name="total_limit" min="1" class="form-control" value="{{ old('total_limit', $coupon?->total_limit) }}" placeholder="{{ translate('messages.Unlimited') }}"></div>
                <div class="col-md-6 col-lg-3"><label class="input-label">{{ translate('messages.Limit Per Passenger') }}</label><input type="number" name="per_user_limit" min="1" class="form-control" required value="{{ old('per_user_limit', $coupon?->per_user_limit ?? 1) }}"></div>
                <div class="col-md-6"><label class="input-label">{{ translate('messages.Pickup Zones') }}</label><select name="zone_ids[]" class="form-control js-select2-custom" multiple data-placeholder="{{ translate('messages.All Zones') }}">@foreach($zones as $zone)<option value="{{ $zone->id }}" @selected(in_array($zone->id, array_map('intval', $selectedZones)))>{{ $zone->name }}</option>@endforeach</select><small class="text-muted">{{ translate('messages.Leave empty for all available zones.') }}</small></div>
                <div class="col-md-6"><label class="input-label">{{ translate('messages.Ride Categories') }}</label><select name="ride_category_ids[]" class="form-control js-select2-custom" multiple data-placeholder="{{ translate('messages.All Categories') }}">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id, array_map('intval', $selectedCategories)))>{{ $category->name }}</option>@endforeach</select><small class="text-muted">{{ translate('messages.Leave empty for all Ride categories.') }}</small></div>
                <div class="col-md-6"><label class="input-label">{{ translate('messages.Payment Methods') }}</label><select name="payment_methods[]" class="form-control js-select2-custom" multiple required>@foreach(['all' => 'All Methods', 'cash' => 'Cash', 'digital' => 'Online', 'wallet' => 'Wallet'] as $value => $label)<option value="{{ $value }}" @selected(in_array($value, $selectedMethods))>{{ translate('messages.'.$label) }}</option>@endforeach</select></div>
                <div class="col-md-3"><label class="input-label">{{ translate('messages.Starts At') }}</label><input type="datetime-local" name="starts_at" class="form-control" required value="{{ old('starts_at', $coupon?->starts_at?->format('Y-m-d\TH:i')) }}"></div>
                <div class="col-md-3"><label class="input-label">{{ translate('messages.Expires At') }}</label><input type="datetime-local" name="expires_at" class="form-control" required value="{{ old('expires_at', $coupon?->expires_at?->format('Y-m-d\TH:i')) }}"></div>
                <div class="col-md-6 d-flex align-items-center"><label class="toggle-switch mb-0"><input type="checkbox" class="toggle-switch-input" name="first_ride_only" value="1" @checked(old('first_ride_only', $coupon?->first_ride_only))><span class="toggle-switch-label"><span class="toggle-switch-indicator"></span></span></label><span class="ml-2">{{ translate('messages.First Ride Only') }}</span></div>
            </div>
            @if($errors->any())<div class="alert alert-danger mt-3 mb-0">{{ $errors->first() }}</div>@endif
            <div class="btn--container justify-content-end mt-3"><button type="reset" class="btn btn--reset">{{ translate('messages.Reset') }}</button><button class="btn btn--primary"><i class="tio-save mr-1"></i>{{ translate($editing ? 'messages.Update Coupon' : 'messages.Create Coupon') }}</button></div>
        </form>
    </div></div>

    <div class="card"><div class="card-header"><h5 class="card-title">{{ translate('messages.Ride Coupon List') }} <span class="badge badge-soft-dark ml-1">{{ $coupons->total() }}</span></h5><form class="search-form min--270"><div class="input-group input--group"><input type="search" name="search" value="{{ $search }}" class="form-control" placeholder="{{ translate('messages.Search title or code') }}"><button class="btn btn--secondary"><i class="tio-search"></i></button></div></form></div>
        <div class="table-responsive"><table class="table table-borderless table-thead-bordered table-align-middle card-table"><thead class="thead-light"><tr><th>{{ translate('messages.Coupon') }}</th><th>{{ translate('messages.Discount') }}</th><th>{{ translate('messages.Scope') }}</th><th>{{ translate('messages.Duration') }}</th><th>{{ translate('messages.Usage') }}</th><th>{{ translate('messages.Status') }}</th><th class="text-center">{{ translate('messages.Action') }}</th></tr></thead><tbody>
        @forelse($coupons as $item)<tr><td><strong>{{ $item->title }}</strong><br><code>{{ $item->code }}</code>@if($item->first_ride_only)<br><span class="badge badge-soft-info mt-1">{{ translate('messages.First Ride Only') }}</span>@endif</td><td><strong>{{ $item->discount_type === 'percent' ? number_format($item->discount, 2).'%' : \App\CentralLogics\Helpers::format_currency($item->discount) }}</strong><br><small class="text-muted">{{ translate('messages.Minimum') }}: {{ \App\CentralLogics\Helpers::format_currency($item->min_fare) }}</small></td><td><small>{{ $item->zone_ids ? count($item->zone_ids).' '.translate('messages.Zones') : translate('messages.All Zones') }}</small><br><small>{{ $item->ride_category_ids ? count($item->ride_category_ids).' '.translate('messages.Categories') : translate('messages.All Categories') }}</small></td><td><small>{{ $item->starts_at->format('d M Y, h:i A') }}</small><br><small class="text-muted">{{ $item->expires_at->format('d M Y, h:i A') }}</small></td><td><a href="{{ route('admin.ride-hailing.coupons.usages', $item) }}" class="font-weight-bold">{{ $item->redeemed_uses }} {{ translate('messages.Redeemed') }}</a><br><small class="text-muted">{{ $item->reserved_uses }} {{ translate('messages.Reserved') }} / {{ $item->total_limit ?: translate('messages.Unlimited') }}</small></td><td><form method="POST" action="{{ route('admin.ride-hailing.coupons.status', $item) }}">@csrf @method('PUT')<label class="toggle-switch mb-0"><input type="checkbox" class="toggle-switch-input" onchange="this.form.submit()" @checked($item->status)><span class="toggle-switch-label"><span class="toggle-switch-indicator"></span></span></label></form></td><td><div class="btn--container justify-content-center"><a href="{{ route('admin.ride-hailing.coupons.edit', $item) }}" class="btn btn-sm btn-outline-primary btn-icon" title="{{ translate('messages.Edit') }}"><i class="tio-edit"></i></a><a href="{{ route('admin.ride-hailing.coupons.usages', $item) }}" class="btn btn-sm btn-outline-info btn-icon" title="{{ translate('messages.Usage') }}"><i class="tio-visible-outlined"></i></a><form method="POST" action="{{ route('admin.ride-hailing.coupons.destroy', $item) }}" onsubmit="return confirm('{{ translate('messages.Delete this unused Ride coupon?') }}')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger btn-icon" title="{{ translate('messages.Delete') }}"><i class="tio-delete"></i></button></form></div></td></tr>@empty<tr><td colspan="7" class="text-center py-5">{{ translate('messages.No Ride coupons found.') }}</td></tr>@endforelse
        </tbody></table></div>@if($coupons->hasPages())<div class="card-footer">{{ $coupons->links() }}</div>@endif
    </div>
</div>
@endsection

@push('script_2')
<script>
    $(function () {
        function syncMaxDiscount() { $('#ride-max-discount-wrap').toggle($('#ride-discount-type').val() === 'percent'); }
        $('#ride-discount-type').on('change', syncMaxDiscount); syncMaxDiscount();
    });
</script>
@endpush
